# Generated by Django 4.2.5 on 2023-10-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='options',
        ),
    ]
